#import "./price.gql"
#import "./stock.gql"


fragment ListProduct on ProductType {
  brand {
    name
  }
  name
  productId
  articleNumber
  alias
  canonicalUrl
  unitPrice {
    ...Price
  }
  productImages {
    fileName
  }
  primaryCategory {
    name
  }
  totalStock {
    ...Stock
  }

}
