#import "./fragments/price.gql"
#import "./fragments/stock.gql"
#import "./fragments/sku.gql"
#import "./fragments/variant.gql"
#import "./fragments/meta.gql"
#import "./fragments/campaign.gql"

query product(
  $alias: String!
  $channelId: String
  $languageId: String
  $marketId: String
) {
  product(
    alias: $alias
    channelId: $channelId
    languageId: $languageId
    marketId: $marketId
  ) {
    productId
    alias
    articleNumber
    canonicalUrl
    name
    meta {
      ...Meta
    }
    brand {
      name
      alias
      canonicalUrl
    }
    productImages {
      fileName
    }
    primaryCategory {
      name
      alias
      canonicalUrl
    }
    unitPrice {
      ...Price
    }
    texts {
      text1
      text2
      text3
    }
    parameterGroups {
      name
      parameterGroupId
      parameters {
        name
        value
        show
        identifier
      }
    }
    skus {
      ...Sku
    }
    totalStock {
      ...Stock
    }
    variantDimensions {
      dimension
      value
      level
      label
    }

    variantGroup {
      variants {
        variants {
          variants {
            ...Variant
          }
          ...Variant
        }
        ...Variant
      }
    }
    discountCampaigns {
      ...Campaign
    }
    rating {
      score
      voteCount
    }
  }
}
